### ISSUE TITLE
Feat(music): Paginated queue

### ISSUE THREAD

**Issue by kyranet** [kyranet/skyra.pw#81]
I know cases where people queued +4800 songs... loading 4800 images would take an enormous time in slow internet, plus the DOM processing done by React to show such long list would be terrible.

**Comment by Favna** [comment]
How about a virtualized infinite loading list instead: 

MUI: https://material-ui.com/components/lists/#virtualized-list
Uses React-window: https://github.com/bvaughn/react-window
and React-window-infinite-loader: https://github.com/bvaughn/react-window-infinite-loader/

(author of react-window and react-window-infinite-loader Brian Vaughn, someone on the ReactJS Core team at Facebook)

**Comment by kyranet** [comment]
Infinite scrolling has several drawbacks, you might want to review them:
https://uxplanet.org/ux-infinite-scrolling-vs-pagination-1030d29376f1

**Comment by Favna** [comment]
We looked into these kind of drawbacks for work as well so let me review them individually:

> Page performance and device resources
This is the very reason react-window exists. It only renders the elements currently visible and anything else gets unrendered. So at any one time only 10-20 (whatever you configure) are actually rendered on the page.

> Item search and location
yeah, location cannot be bookmarked, but whether this is required all depends on what you're making, and what they are referring to is changing the URL (for example with `?page=2` in the querystring) when paginating. Even with pagination I don't personally see a reason to do this for Skyra's music dashboard since pages differ so quickly and so much.

Item search is totally possible because react-window expects the full list to be passed as the data so you can just shorten that variable and React will re-render the list. You'd pretty much apply the same concept for pagination anyway (using `Array.slice`). For example one super easy way to paginate with customizable amount of rows per page:
```js
DataArray.slice(currentPage * rowsPerPage, currentPage * rowsPerPage + rowsPerPage)
```

> Irrelevant scroll bar
Well sure but I'd argue that only applies when the entire content is the infinite scrolling list rather than a small subsection. Furthermore, right now the scroll bar is on the entire page so if anything it would make more sense to add a scrollbar to only the list rather and keep the whole page 1 viewport height tall. 
![image](https://user-images.githubusercontent.com/4019718/71449239-05b40080-2749-11ea-831c-f17300a72331.png)

> Lack of a footer
This is absolute bullshit and only applies if, again, the entire page is the list and there is no DOM elements around it at all. This will totally not apply to us because the list is child component. 

---

I went over this selfsame article with the UXers at work a long while ago and we both came to the conclusion that it was written by a UXer who had the shits knowledge of what is actually possible in custom made apps that are not using lousy templates these days. Most of his cons completely fall apart when you realize how React or any modern web framework for that matter actually works.

**Comment by Favna** [comment]
I created a CodeSandbox showing react-window + Material-UI List while also having ListItemAvatar (for the thumbnails) and some secondary actions for the delete button: https://codesandbox.io/s/material-demo-g6ggg?fontsize=14&hidenavigation=1&module=%2Fdemo.tsx&theme=dark

Or to get just the preview for viewing on mobile: https://codesandbox.io/s/material-demo-g6ggg?fontsize=14&hidenavigation=1&module=%2Fdemo.tsx&theme=dark&view=preview
